name: packer

on: workflow_dispatch

env:
  CHECKPOINT_DISABLE: "1"
  PACKER_NO_COLOR: "1"
  #PACKER_CONFIG_DIR: "${{ github.workspace }}/.packer"
  PACKER_PLUGIN_PATH: "${{ github.workspace }}/.packer/plugins"
  PACKER_CACHE_DIR: "${{ github.workspace }}/.packer/cache"

jobs:
  packer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup HashiCorp Packer
        uses: hashicorp/setup-packer@v3
        with:
          version: "1.11.2"
      - name: Prepare Packer cache directories
        run: mkdir -vp ${{ env.PACKER_PLUGIN_PATH }} ${{ env.PACKER_CACHE_DIR }}
      - name: Restore Packer plugins
        id: restore-packer-plugins
        uses: actions/cache/restore@v4
        with:
          path: ${{ env.PACKER_PLUGIN_PATH }}
          key: packer-plugins-${{ runner.os }}-${{ hashFiles('.packer/plugins/**') }}
      - name: Run `packer init`
        run: packer init .
        env:
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
      - name: Cache Packer plugins
        uses: actions/cache/save@v4
        with:
          path: ${{ env.PACKER_PLUGIN_PATH }}
          key: ${{ steps.restore-packer-plugins.outputs.cache-primary-key }}
      - name: Run `packer validate`
        run: packer validate .
        env:
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
      - name: Run `packer build`
        run: packer build .
        env:
          HCLOUD_TOKEN: ${{ secrets.HCLOUD_TOKEN }}
